DROP TABLE collocations IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE collocations
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  mainword             VARCHAR(255)            NOT NULL,
  pairword            VARCHAR(255)            NOT NULL
);

CREATE UNIQUE INDEX collocations_unique_mainword_pairword_idx
  ON collocations (mainword, pairword)